CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    address TEXT NOT NULL,
    area VARCHAR(255) DEFAULT '',
    city VARCHAR(255) DEFAULT '',
    state VARCHAR(255) DEFAULT '',
    country VARCHAR(255) DEFAULT '',
    country_code VARCHAR(10) NOT NULL,
    zipcode VARCHAR(20) DEFAULT '',
    latitude VARCHAR(20) NOT NULL,
    longitude VARCHAR(20) NOT NULL,
    bio TEXT DEFAULT '',
    device_type VARCHAR(50) DEFAULT '',
    device_token VARCHAR(255) DEFAULT '',
    avatar VARCHAR(255) DEFAULT '',
    role ENUM('user', 'admin') DEFAULT 'user',
    status ENUM('active', 'inactive') DEFAULT 'active',
    phone_verified_at DATETIME DEFAULT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
